from . import MSVCSetup
from . import SDLSetup
from . import CUDASetup
from . import OpenGLSetup
from . import DSetup
from . import LatexSetup
from . import DiaSetup
from . import GnuplotSetup
from . import NotationSetup
